# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/bau/ZedBoard/hw/proj/hw.srcs/sources_1/bd/system/ip/system_video_scaler_c_0/system_video_scaler_c_0.xci
# IP: The module: 'system_video_scaler_c_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/bau/ZedBoard/hw/proj/hw.gen/sources_1/bd/system/ip/system_video_scaler_c_0/constraints/video_scaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_scaler_c_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/bau/ZedBoard/hw/proj/hw.srcs/sources_1/bd/system/ip/system_video_scaler_c_0/system_video_scaler_c_0.xci
# IP: The module: 'system_video_scaler_c_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/bau/ZedBoard/hw/proj/hw.gen/sources_1/bd/system/ip/system_video_scaler_c_0/constraints/video_scaler_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_scaler_c_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
