#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ZYNQ
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver MIPI_CSI_2_RX */
#define XPAR_MIPI_CSI_2_RX_NUM_INSTANCES 4

/* Definitions for peripheral MIPI_CSI_2_RX_A */
#define XPAR_MIPI_CSI_2_RX_A_DEVICE_ID 0
#define XPAR_MIPI_CSI_2_RX_A_S_AXI_LITE_BASEADDR 0x43C00000
#define XPAR_MIPI_CSI_2_RX_A_S_AXI_LITE_HIGHADDR 0x43C0FFFF


/* Definitions for peripheral MIPI_CSI_2_RX_B */
#define XPAR_MIPI_CSI_2_RX_B_DEVICE_ID 1
#define XPAR_MIPI_CSI_2_RX_B_S_AXI_LITE_BASEADDR 0x43C10000
#define XPAR_MIPI_CSI_2_RX_B_S_AXI_LITE_HIGHADDR 0x43C1FFFF


/* Definitions for peripheral MIPI_CSI_2_RX_C */
#define XPAR_MIPI_CSI_2_RX_C_DEVICE_ID 2
#define XPAR_MIPI_CSI_2_RX_C_S_AXI_LITE_BASEADDR 0x43C20000
#define XPAR_MIPI_CSI_2_RX_C_S_AXI_LITE_HIGHADDR 0x43C2FFFF


/* Definitions for peripheral MIPI_CSI_2_RX_D */
#define XPAR_MIPI_CSI_2_RX_D_DEVICE_ID 3
#define XPAR_MIPI_CSI_2_RX_D_S_AXI_LITE_BASEADDR 0x43C30000
#define XPAR_MIPI_CSI_2_RX_D_S_AXI_LITE_HIGHADDR 0x43C3FFFF


/******************************************************************/

/* Definitions for driver MIPI_D_PHY_RX */
#define XPAR_MIPI_D_PHY_RX_NUM_INSTANCES 4

/* Definitions for peripheral MIPI_D_PHY_RX_A */
#define XPAR_MIPI_D_PHY_RX_A_DEVICE_ID 0
#define XPAR_MIPI_D_PHY_RX_A_S_AXI_LITE_BASEADDR 0x43C40000
#define XPAR_MIPI_D_PHY_RX_A_S_AXI_LITE_HIGHADDR 0x43C4FFFF


/* Definitions for peripheral MIPI_D_PHY_RX_B */
#define XPAR_MIPI_D_PHY_RX_B_DEVICE_ID 1
#define XPAR_MIPI_D_PHY_RX_B_S_AXI_LITE_BASEADDR 0x43C50000
#define XPAR_MIPI_D_PHY_RX_B_S_AXI_LITE_HIGHADDR 0x43C5FFFF


/* Definitions for peripheral MIPI_D_PHY_RX_C */
#define XPAR_MIPI_D_PHY_RX_C_DEVICE_ID 2
#define XPAR_MIPI_D_PHY_RX_C_S_AXI_LITE_BASEADDR 0x43C60000
#define XPAR_MIPI_D_PHY_RX_C_S_AXI_LITE_HIGHADDR 0x43C6FFFF


/* Definitions for peripheral MIPI_D_PHY_RX_D */
#define XPAR_MIPI_D_PHY_RX_D_DEVICE_ID 3
#define XPAR_MIPI_D_PHY_RX_D_S_AXI_LITE_BASEADDR 0x43C70000
#define XPAR_MIPI_D_PHY_RX_D_S_AXI_LITE_HIGHADDR 0x43C7FFFF


/******************************************************************/

/* Definitions for driver AXIVDMA */
#define XPAR_XAXIVDMA_NUM_INSTANCES 4U

/* Definitions for peripheral AXI_VDMA_A */
#define XPAR_AXI_VDMA_A_DEVICE_ID 0U
#define XPAR_AXI_VDMA_A_BASEADDR 0x43000000U
#define XPAR_AXI_VDMA_A_HIGHADDR 0x4300FFFFU
#define XPAR_AXI_VDMA_A_NUM_FSTORES 4U
#define XPAR_AXI_VDMA_A_INCLUDE_MM2S 1U
#define XPAR_AXI_VDMA_A_INCLUDE_MM2S_DRE 0U
#define XPAR_AXI_VDMA_A_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_A_INCLUDE_S2MM 1U
#define XPAR_AXI_VDMA_A_INCLUDE_S2MM_DRE 0U
#define XPAR_AXI_VDMA_A_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_A_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_A_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_A_MM2S_GENLOCK_MODE 1U
#define XPAR_AXI_VDMA_A_MM2S_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXI_VDMA_A_S2MM_GENLOCK_MODE 1U
#define XPAR_AXI_VDMA_A_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXI_VDMA_A_INCLUDE_SG 0U
#define XPAR_AXI_VDMA_A_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXI_VDMA_A_USE_FSYNC 1U
#define XPAR_AXI_VDMA_A_FLUSH_ON_FSYNC 1U
#define XPAR_AXI_VDMA_A_MM2S_LINEBUFFER_DEPTH 1024U
#define XPAR_AXI_VDMA_A_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXI_VDMA_A_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXI_VDMA_A_S2MM_SOF_ENABLE 1U
#define XPAR_AXI_VDMA_A_M_AXIS_MM2S_TDATA_WIDTH 24U
#define XPAR_AXI_VDMA_A_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_5 1U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXI_VDMA_A_ENABLE_DEBUG_ALL 0U
#define XPAR_AXI_VDMA_A_ADDR_WIDTH 32U
#define XPAR_AXI_VDMA_A_ENABLE_VERT_FLIP 0U


/* Definitions for peripheral AXI_VDMA_B */
#define XPAR_AXI_VDMA_B_DEVICE_ID 1U
#define XPAR_AXI_VDMA_B_BASEADDR 0x43010000U
#define XPAR_AXI_VDMA_B_HIGHADDR 0x4301FFFFU
#define XPAR_AXI_VDMA_B_NUM_FSTORES 4U
#define XPAR_AXI_VDMA_B_INCLUDE_MM2S 0U
#define XPAR_AXI_VDMA_B_INCLUDE_MM2S_DRE 0U
#define XPAR_AXI_VDMA_B_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_B_INCLUDE_S2MM 1U
#define XPAR_AXI_VDMA_B_INCLUDE_S2MM_DRE 0U
#define XPAR_AXI_VDMA_B_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_B_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_B_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_B_MM2S_GENLOCK_MODE 0U
#define XPAR_AXI_VDMA_B_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXI_VDMA_B_S2MM_GENLOCK_MODE 1U
#define XPAR_AXI_VDMA_B_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXI_VDMA_B_INCLUDE_SG 0U
#define XPAR_AXI_VDMA_B_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXI_VDMA_B_USE_FSYNC 1U
#define XPAR_AXI_VDMA_B_FLUSH_ON_FSYNC 1U
#define XPAR_AXI_VDMA_B_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXI_VDMA_B_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXI_VDMA_B_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXI_VDMA_B_S2MM_SOF_ENABLE 1U
#define XPAR_AXI_VDMA_B_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXI_VDMA_B_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXI_VDMA_B_ENABLE_DEBUG_ALL 0U
#define XPAR_AXI_VDMA_B_ADDR_WIDTH 32U
#define XPAR_AXI_VDMA_B_ENABLE_VERT_FLIP 0U


/* Definitions for peripheral AXI_VDMA_C */
#define XPAR_AXI_VDMA_C_DEVICE_ID 2U
#define XPAR_AXI_VDMA_C_BASEADDR 0x43020000U
#define XPAR_AXI_VDMA_C_HIGHADDR 0x4302FFFFU
#define XPAR_AXI_VDMA_C_NUM_FSTORES 4U
#define XPAR_AXI_VDMA_C_INCLUDE_MM2S 0U
#define XPAR_AXI_VDMA_C_INCLUDE_MM2S_DRE 0U
#define XPAR_AXI_VDMA_C_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_C_INCLUDE_S2MM 1U
#define XPAR_AXI_VDMA_C_INCLUDE_S2MM_DRE 0U
#define XPAR_AXI_VDMA_C_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_C_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_C_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_C_MM2S_GENLOCK_MODE 0U
#define XPAR_AXI_VDMA_C_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXI_VDMA_C_S2MM_GENLOCK_MODE 1U
#define XPAR_AXI_VDMA_C_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXI_VDMA_C_INCLUDE_SG 0U
#define XPAR_AXI_VDMA_C_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXI_VDMA_C_USE_FSYNC 1U
#define XPAR_AXI_VDMA_C_FLUSH_ON_FSYNC 1U
#define XPAR_AXI_VDMA_C_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXI_VDMA_C_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXI_VDMA_C_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXI_VDMA_C_S2MM_SOF_ENABLE 1U
#define XPAR_AXI_VDMA_C_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXI_VDMA_C_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXI_VDMA_C_ENABLE_DEBUG_ALL 0U
#define XPAR_AXI_VDMA_C_ADDR_WIDTH 32U
#define XPAR_AXI_VDMA_C_ENABLE_VERT_FLIP 0U


/* Definitions for peripheral AXI_VDMA_D */
#define XPAR_AXI_VDMA_D_DEVICE_ID 3U
#define XPAR_AXI_VDMA_D_BASEADDR 0x43030000U
#define XPAR_AXI_VDMA_D_HIGHADDR 0x4303FFFFU
#define XPAR_AXI_VDMA_D_NUM_FSTORES 4U
#define XPAR_AXI_VDMA_D_INCLUDE_MM2S 0U
#define XPAR_AXI_VDMA_D_INCLUDE_MM2S_DRE 0U
#define XPAR_AXI_VDMA_D_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_D_INCLUDE_S2MM 1U
#define XPAR_AXI_VDMA_D_INCLUDE_S2MM_DRE 0U
#define XPAR_AXI_VDMA_D_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_D_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_D_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_D_MM2S_GENLOCK_MODE 0U
#define XPAR_AXI_VDMA_D_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXI_VDMA_D_S2MM_GENLOCK_MODE 1U
#define XPAR_AXI_VDMA_D_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXI_VDMA_D_INCLUDE_SG 0U
#define XPAR_AXI_VDMA_D_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXI_VDMA_D_USE_FSYNC 1U
#define XPAR_AXI_VDMA_D_FLUSH_ON_FSYNC 1U
#define XPAR_AXI_VDMA_D_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXI_VDMA_D_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXI_VDMA_D_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXI_VDMA_D_S2MM_SOF_ENABLE 1U
#define XPAR_AXI_VDMA_D_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXI_VDMA_D_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXI_VDMA_D_ENABLE_DEBUG_ALL 0U
#define XPAR_AXI_VDMA_D_ADDR_WIDTH 32U
#define XPAR_AXI_VDMA_D_ENABLE_VERT_FLIP 0U


/******************************************************************/

/* Canonical definitions for peripheral AXI_VDMA_A */
#define XPAR_AXIVDMA_0_DEVICE_ID XPAR_AXI_VDMA_A_DEVICE_ID
#define XPAR_AXIVDMA_0_BASEADDR 0x43000000U
#define XPAR_AXIVDMA_0_HIGHADDR 0x4300FFFFU
#define XPAR_AXIVDMA_0_NUM_FSTORES 4U
#define XPAR_AXIVDMA_0_INCLUDE_MM2S 1U
#define XPAR_AXIVDMA_0_INCLUDE_MM2S_DRE 0U
#define XPAR_AXIVDMA_0_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXIVDMA_0_INCLUDE_S2MM 1U
#define XPAR_AXIVDMA_0_INCLUDE_S2MM_DRE 0U
#define XPAR_AXIVDMA_0_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXIVDMA_0_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_0_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_MODE 1U
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_MODE 1U
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXIVDMA_0_INCLUDE_SG 0U
#define XPAR_AXIVDMA_0_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXIVDMA_0_USE_FSYNC 1U
#define XPAR_AXIVDMA_0_FLUSH_ON_FSYNC 1U
#define XPAR_AXIVDMA_0_MM2S_LINEBUFFER_DEPTH 1024U
#define XPAR_AXIVDMA_0_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXIVDMA_0_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXIVDMA_0_S2MM_SOF_ENABLE 1U
#define XPAR_AXIVDMA_0_M_AXIS_MM2S_TDATA_WIDTH 24U
#define XPAR_AXIVDMA_0_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_5 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_ALL 0U
#define XPAR_AXIVDMA_0_c_addr_width 32U
#define XPAR_AXIVDMA_0_c_enable_vert_flip 0U

/* Canonical definitions for peripheral AXI_VDMA_B */
#define XPAR_AXIVDMA_1_DEVICE_ID XPAR_AXI_VDMA_B_DEVICE_ID
#define XPAR_AXIVDMA_1_BASEADDR 0x43010000U
#define XPAR_AXIVDMA_1_HIGHADDR 0x4301FFFFU
#define XPAR_AXIVDMA_1_NUM_FSTORES 4U
#define XPAR_AXIVDMA_1_INCLUDE_MM2S 0U
#define XPAR_AXIVDMA_1_INCLUDE_MM2S_DRE 0U
#define XPAR_AXIVDMA_1_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXIVDMA_1_INCLUDE_S2MM 1U
#define XPAR_AXIVDMA_1_INCLUDE_S2MM_DRE 0U
#define XPAR_AXIVDMA_1_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXIVDMA_1_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_1_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_1_MM2S_GENLOCK_MODE 0U
#define XPAR_AXIVDMA_1_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_1_S2MM_GENLOCK_MODE 1U
#define XPAR_AXIVDMA_1_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXIVDMA_1_INCLUDE_SG 0U
#define XPAR_AXIVDMA_1_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXIVDMA_1_USE_FSYNC 1U
#define XPAR_AXIVDMA_1_FLUSH_ON_FSYNC 1U
#define XPAR_AXIVDMA_1_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXIVDMA_1_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXIVDMA_1_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXIVDMA_1_S2MM_SOF_ENABLE 1U
#define XPAR_AXIVDMA_1_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXIVDMA_1_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_ALL 0U
#define XPAR_AXIVDMA_1_c_addr_width 32U
#define XPAR_AXIVDMA_1_c_enable_vert_flip 0U

/* Canonical definitions for peripheral AXI_VDMA_C */
#define XPAR_AXIVDMA_2_DEVICE_ID XPAR_AXI_VDMA_C_DEVICE_ID
#define XPAR_AXIVDMA_2_BASEADDR 0x43020000U
#define XPAR_AXIVDMA_2_HIGHADDR 0x4302FFFFU
#define XPAR_AXIVDMA_2_NUM_FSTORES 4U
#define XPAR_AXIVDMA_2_INCLUDE_MM2S 0U
#define XPAR_AXIVDMA_2_INCLUDE_MM2S_DRE 0U
#define XPAR_AXIVDMA_2_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXIVDMA_2_INCLUDE_S2MM 1U
#define XPAR_AXIVDMA_2_INCLUDE_S2MM_DRE 0U
#define XPAR_AXIVDMA_2_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXIVDMA_2_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_2_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_2_MM2S_GENLOCK_MODE 0U
#define XPAR_AXIVDMA_2_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_2_S2MM_GENLOCK_MODE 1U
#define XPAR_AXIVDMA_2_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXIVDMA_2_INCLUDE_SG 0U
#define XPAR_AXIVDMA_2_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXIVDMA_2_USE_FSYNC 1U
#define XPAR_AXIVDMA_2_FLUSH_ON_FSYNC 1U
#define XPAR_AXIVDMA_2_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXIVDMA_2_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXIVDMA_2_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXIVDMA_2_S2MM_SOF_ENABLE 1U
#define XPAR_AXIVDMA_2_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXIVDMA_2_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXIVDMA_2_ENABLE_DEBUG_ALL 0U
#define XPAR_AXIVDMA_2_c_addr_width 32U
#define XPAR_AXIVDMA_2_c_enable_vert_flip 0U

/* Canonical definitions for peripheral AXI_VDMA_D */
#define XPAR_AXIVDMA_3_DEVICE_ID XPAR_AXI_VDMA_D_DEVICE_ID
#define XPAR_AXIVDMA_3_BASEADDR 0x43030000U
#define XPAR_AXIVDMA_3_HIGHADDR 0x4303FFFFU
#define XPAR_AXIVDMA_3_NUM_FSTORES 4U
#define XPAR_AXIVDMA_3_INCLUDE_MM2S 0U
#define XPAR_AXIVDMA_3_INCLUDE_MM2S_DRE 0U
#define XPAR_AXIVDMA_3_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXIVDMA_3_INCLUDE_S2MM 1U
#define XPAR_AXIVDMA_3_INCLUDE_S2MM_DRE 0U
#define XPAR_AXIVDMA_3_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXIVDMA_3_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_3_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_3_MM2S_GENLOCK_MODE 0U
#define XPAR_AXIVDMA_3_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_3_S2MM_GENLOCK_MODE 1U
#define XPAR_AXIVDMA_3_S2MM_GENLOCK_NUM_MASTERS 4U
#define XPAR_AXIVDMA_3_INCLUDE_SG 0U
#define XPAR_AXIVDMA_3_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXIVDMA_3_USE_FSYNC 1U
#define XPAR_AXIVDMA_3_FLUSH_ON_FSYNC 1U
#define XPAR_AXIVDMA_3_MM2S_LINEBUFFER_DEPTH 512U
#define XPAR_AXIVDMA_3_S2MM_LINEBUFFER_DEPTH 1024U
#define XPAR_AXIVDMA_3_INCLUDE_INTERNAL_GENLOCK 0U
#define XPAR_AXIVDMA_3_S2MM_SOF_ENABLE 1U
#define XPAR_AXIVDMA_3_M_AXIS_MM2S_TDATA_WIDTH 32U
#define XPAR_AXIVDMA_3_S_AXIS_S2MM_TDATA_WIDTH 24U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_13 1U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXIVDMA_3_ENABLE_DEBUG_ALL 0U
#define XPAR_AXIVDMA_3_c_addr_width 32U
#define XPAR_AXIVDMA_3_c_enable_vert_flip 0U


/******************************************************************/

/* Definitions for driver CLK_WIZ */
#define XPAR_XCLK_WIZ_NUM_INSTANCES 1

/* Definitions for peripheral VIDEO_DYNCLK */
#define XPAR_VIDEO_DYNCLK_DEVICE_ID 0
#define XPAR_VIDEO_DYNCLK_BASEADDR 0x43C80000
#define XPAR_VIDEO_DYNCLK_HIGHADDR 0x43C8FFFF
#define XPAR_VIDEO_DYNCLK_ENABLE_CLOCK_MONITOR 0
#define XPAR_VIDEO_DYNCLK_ENABLE_USER_CLOCK0 0
#define XPAR_VIDEO_DYNCLK_ENABLE_USER_CLOCK1 0
#define XPAR_VIDEO_DYNCLK_ENABLE_USER_CLOCK2 0
#define XPAR_VIDEO_DYNCLK_ENABLE_USER_CLOCK3 0
#define XPAR_VIDEO_DYNCLK_REF_CLK_FREQ 100.0
#define XPAR_VIDEO_DYNCLK_USER_CLK_FREQ0 100.0
#define XPAR_VIDEO_DYNCLK_USER_CLK_FREQ1 100.0
#define XPAR_VIDEO_DYNCLK_USER_CLK_FREQ2 100.0
#define XPAR_VIDEO_DYNCLK_USER_CLK_FREQ3 100.0
#define XPAR_VIDEO_DYNCLK_PRECISION 1
#define XPAR_VIDEO_DYNCLK_ENABLE_PLL0 0
#define XPAR_VIDEO_DYNCLK_ENABLE_PLL1 0
#define XPAR_VIDEO_DYNCLK_PRIM_IN_FREQ 100.000
#define XPAR_VIDEO_DYNCLK_NUM_OUT_CLKS 1


/******************************************************************/

/* Canonical definitions for peripheral VIDEO_DYNCLK */
#define XPAR_CLK_WIZ_0_DEVICE_ID XPAR_VIDEO_DYNCLK_DEVICE_ID
#define XPAR_CLK_WIZ_0_BASEADDR 0x43C80000
#define XPAR_CLK_WIZ_0_HIGHADDR 0x43C8FFFF
#define XPAR_CLK_WIZ_0_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_0_REF_CLK_FREQ 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ0 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ1 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ2 100.0
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ3 100.0
#define XPAR_CLK_WIZ_0_PRECISION 1
#define XPAR_CLK_WIZ_0_Enable_PLL0 0
#define XPAR_CLK_WIZ_0_Enable_PLL1 0
#define XPAR_CLK_WIZ_0_PRIM_IN_FREQ 100.000
#define XPAR_CLK_WIZ_0_NUM_OUT_CLKS 1


/******************************************************************/


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x1FFFFFFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0U
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000U
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000U
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50
#define XPAR_PS7_ETHERNET_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PS7_ETHERNET_0_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/


/* Peripheral Definitions for peripheral AXI_GAMMACORRECTION_A */
#define XPAR_AXI_GAMMACORRECTION_A_BASEADDR 0x43CE0000
#define XPAR_AXI_GAMMACORRECTION_A_HIGHADDR 0x43CEFFFF


/* Peripheral Definitions for peripheral AXI_GAMMACORRECTION_B */
#define XPAR_AXI_GAMMACORRECTION_B_BASEADDR 0x43CF0000
#define XPAR_AXI_GAMMACORRECTION_B_HIGHADDR 0x43CFFFFF


/* Peripheral Definitions for peripheral AXI_GAMMACORRECTION_C */
#define XPAR_AXI_GAMMACORRECTION_C_BASEADDR 0x43D00000
#define XPAR_AXI_GAMMACORRECTION_C_HIGHADDR 0x43D0FFFF


/* Peripheral Definitions for peripheral AXI_GAMMACORRECTION_D */
#define XPAR_AXI_GAMMACORRECTION_D_BASEADDR 0x43D10000
#define XPAR_AXI_GAMMACORRECTION_D_HIGHADDR 0x43D1FFFF


/* Peripheral Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Peripheral Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Peripheral Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Peripheral Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Peripheral Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Peripheral Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Peripheral Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Peripheral Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Peripheral Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Peripheral Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Peripheral Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Peripheral Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Peripheral Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Peripheral Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFCFFFFFF


/* Peripheral Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Peripheral Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Peripheral Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Peripheral Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/******************************************************************/


/* Canonical Definitions for peripheral AXI_GAMMACORRECTION_A */
#define XPAR_AXI_GAMMACORRECTION_0_BASEADDR 0x43CE0000
#define XPAR_AXI_GAMMACORRECTION_0_HIGHADDR 0x43CEFFFF


/* Canonical Definitions for peripheral AXI_GAMMACORRECTION_B */
#define XPAR_AXI_GAMMACORRECTION_1_BASEADDR 0x43CF0000
#define XPAR_AXI_GAMMACORRECTION_1_HIGHADDR 0x43CFFFFF


/* Canonical Definitions for peripheral AXI_GAMMACORRECTION_C */
#define XPAR_AXI_GAMMACORRECTION_2_BASEADDR 0x43D00000
#define XPAR_AXI_GAMMACORRECTION_2_HIGHADDR 0x43D0FFFF


/* Canonical Definitions for peripheral AXI_GAMMACORRECTION_D */
#define XPAR_AXI_GAMMACORRECTION_3_BASEADDR 0x43D10000
#define XPAR_AXI_GAMMACORRECTION_3_HIGHADDR 0x43D1FFFF






































/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral AXI_CAMA_BTA */
#define XPAR_AXI_CAMA_BTA_BASEADDR 0x41200000
#define XPAR_AXI_CAMA_BTA_HIGHADDR 0x4120FFFF
#define XPAR_AXI_CAMA_BTA_DEVICE_ID 0
#define XPAR_AXI_CAMA_BTA_INTERRUPT_PRESENT 0
#define XPAR_AXI_CAMA_BTA_IS_DUAL 0


/* Definitions for peripheral AXI_CAMA_GPIO */
#define XPAR_AXI_CAMA_GPIO_BASEADDR 0x41210000
#define XPAR_AXI_CAMA_GPIO_HIGHADDR 0x4121FFFF
#define XPAR_AXI_CAMA_GPIO_DEVICE_ID 1
#define XPAR_AXI_CAMA_GPIO_INTERRUPT_PRESENT 0
#define XPAR_AXI_CAMA_GPIO_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_CAMA_BTA */
#define XPAR_GPIO_0_BASEADDR 0x41200000
#define XPAR_GPIO_0_HIGHADDR 0x4120FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_CAMA_BTA_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral AXI_CAMA_GPIO */
#define XPAR_GPIO_1_BASEADDR 0x41210000
#define XPAR_GPIO_1_HIGHADDR 0x4121FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_AXI_CAMA_GPIO_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_I2C_0 */
#define XPAR_PS7_I2C_0_DEVICE_ID 0
#define XPAR_PS7_I2C_0_BASEADDR 0xE0004000
#define XPAR_PS7_I2C_0_HIGHADDR 0xE0004FFF
#define XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Canonical definitions for peripheral PS7_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PS7_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xE0004000
#define XPAR_XIICPS_0_HIGHADDR 0xE0004FFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Definition for input Clock */
/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_PS7_QSPI_0_QSPI_MODE 0
#define XPAR_PS7_QSPI_0_QSPI_BUS_WIDTH 2


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_XQSPIPS_0_QSPI_MODE 0
#define XPAR_XQSPIPS_0_QSPI_BUS_WIDTH 2


/******************************************************************/

/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_VTG_IRQ_INTR 61U
#define XPAR_FABRIC_AXI_VDMA_A_MM2S_INTROUT_INTR 62U
#define XPAR_FABRIC_AXI_VDMA_A_S2MM_INTROUT_INTR 63U
#define XPAR_FABRIC_AXI_VDMA_B_S2MM_INTROUT_INTR 64U
#define XPAR_FABRIC_AXI_VDMA_C_S2MM_INTROUT_INTR 65U
#define XPAR_FABRIC_AXI_VDMA_D_S2MM_INTROUT_INTR 66U

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_VTC_0_VEC_ID XPAR_FABRIC_VTG_IRQ_INTR
#define XPAR_FABRIC_AXIVDMA_0_MM2S_INTROUT_VEC_ID XPAR_FABRIC_AXI_VDMA_A_MM2S_INTROUT_INTR
#define XPAR_FABRIC_AXIVDMA_0_S2MM_INTROUT_VEC_ID XPAR_FABRIC_AXI_VDMA_A_S2MM_INTROUT_INTR
#define XPAR_FABRIC_AXIVDMA_1_VEC_ID XPAR_FABRIC_AXI_VDMA_B_S2MM_INTROUT_INTR
#define XPAR_FABRIC_AXIVDMA_2_VEC_ID XPAR_FABRIC_AXI_VDMA_C_S2MM_INTROUT_INTR
#define XPAR_FABRIC_AXIVDMA_3_VEC_ID XPAR_FABRIC_AXI_VDMA_D_S2MM_INTROUT_INTR

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0U
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100U
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FFU
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 100000000
#define XPAR_PS7_SD_0_HAS_CD 1
#define XPAR_PS7_SD_0_HAS_WP 1
#define XPAR_PS7_SD_0_BUS_WIDTH 0
#define XPAR_PS7_SD_0_MIO_BANK 0
#define XPAR_PS7_SD_0_HAS_EMIO 0
#define XPAR_PS7_SD_0_SLOT_TYPE 0


/******************************************************************/

#define XPAR_PS7_SD_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 100000000
#define XPAR_XSDPS_0_HAS_CD 1
#define XPAR_XSDPS_0_HAS_WP 1
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 0
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_SLOT_TYPE 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 0
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 50000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 50000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definition for input Clock */
/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Definitions for driver VIDEO_SCALER */
#define XPAR_XVIDEO_SCALER_NUM_INSTANCES 4

/* Definitions for peripheral VIDEO_SCALER_A */
#define XPAR_VIDEO_SCALER_A_DEVICE_ID 0
#define XPAR_VIDEO_SCALER_A_S_AXI_CTRL_BASEADDR 0x43C90000
#define XPAR_VIDEO_SCALER_A_S_AXI_CTRL_HIGHADDR 0x43C9FFFF


/* Definitions for peripheral VIDEO_SCALER_B */
#define XPAR_VIDEO_SCALER_B_DEVICE_ID 1
#define XPAR_VIDEO_SCALER_B_S_AXI_CTRL_BASEADDR 0x43CA0000
#define XPAR_VIDEO_SCALER_B_S_AXI_CTRL_HIGHADDR 0x43CAFFFF


/* Definitions for peripheral VIDEO_SCALER_C */
#define XPAR_VIDEO_SCALER_C_DEVICE_ID 2
#define XPAR_VIDEO_SCALER_C_S_AXI_CTRL_BASEADDR 0x43CB0000
#define XPAR_VIDEO_SCALER_C_S_AXI_CTRL_HIGHADDR 0x43CBFFFF


/* Definitions for peripheral VIDEO_SCALER_D */
#define XPAR_VIDEO_SCALER_D_DEVICE_ID 3
#define XPAR_VIDEO_SCALER_D_S_AXI_CTRL_BASEADDR 0x43CC0000
#define XPAR_VIDEO_SCALER_D_S_AXI_CTRL_HIGHADDR 0x43CCFFFF


/******************************************************************/

/* Canonical definitions for peripheral VIDEO_SCALER_A */
#define XPAR_XVIDEO_SCALER_0_DEVICE_ID XPAR_VIDEO_SCALER_A_DEVICE_ID
#define XPAR_XVIDEO_SCALER_0_S_AXI_CTRL_BASEADDR 0x43C90000
#define XPAR_XVIDEO_SCALER_0_S_AXI_CTRL_HIGHADDR 0x43C9FFFF

/* Canonical definitions for peripheral VIDEO_SCALER_B */
#define XPAR_XVIDEO_SCALER_1_DEVICE_ID XPAR_VIDEO_SCALER_B_DEVICE_ID
#define XPAR_XVIDEO_SCALER_1_S_AXI_CTRL_BASEADDR 0x43CA0000
#define XPAR_XVIDEO_SCALER_1_S_AXI_CTRL_HIGHADDR 0x43CAFFFF

/* Canonical definitions for peripheral VIDEO_SCALER_C */
#define XPAR_XVIDEO_SCALER_2_DEVICE_ID XPAR_VIDEO_SCALER_C_DEVICE_ID
#define XPAR_XVIDEO_SCALER_2_S_AXI_CTRL_BASEADDR 0x43CB0000
#define XPAR_XVIDEO_SCALER_2_S_AXI_CTRL_HIGHADDR 0x43CBFFFF

/* Canonical definitions for peripheral VIDEO_SCALER_D */
#define XPAR_XVIDEO_SCALER_3_DEVICE_ID XPAR_VIDEO_SCALER_D_DEVICE_ID
#define XPAR_XVIDEO_SCALER_3_S_AXI_CTRL_BASEADDR 0x43CC0000
#define XPAR_XVIDEO_SCALER_3_S_AXI_CTRL_HIGHADDR 0x43CCFFFF


/******************************************************************/

/* Definitions for driver VTC */
#define XPAR_XVTC_NUM_INSTANCES 1

/* Definitions for peripheral VTG */
#define XPAR_VTG_DEVICE_ID 0
#define XPAR_VTG_BASEADDR 0x43CD0000
#define XPAR_VTG_HIGHADDR 0x43CDFFFF
#define XPAR_VTG_GENERATE_EN 1
#define XPAR_VTG_DETECT_EN 0
#define XPAR_VTG_DET_HSYNC_EN 1
#define XPAR_VTG_DET_VSYNC_EN 1
#define XPAR_VTG_DET_HBLANK_EN 1
#define XPAR_VTG_DET_VBLANK_EN 1
#define XPAR_VTG_DET_AVIDEO_EN 1
#define XPAR_VTG_DET_ACHROMA_EN 0


/******************************************************************/

/* Canonical definitions for peripheral VTG */
#define XPAR_VTC_0_DEVICE_ID XPAR_VTG_DEVICE_ID
#define XPAR_VTC_0_BASEADDR 0x43CD0000
#define XPAR_VTC_0_HIGHADDR 0x43CDFFFF
#define XPAR_VTC_0_GENERATE_EN 1
#define XPAR_VTC_0_DETECT_EN 0
#define XPAR_VTC_0_DET_HSYNC_EN 1
#define XPAR_VTC_0_DET_VSYNC_EN 1
#define XPAR_VTC_0_DET_HBLANK_EN 1
#define XPAR_VTC_0_DET_VBLANK_EN 1
#define XPAR_VTC_0_DET_AVIDEO_EN 1
#define XPAR_VTC_0_DET_ACHROMA_EN 0


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

#endif  /* end of protection macro */
