# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_master_XDC_RevC_D_v3.xdc

# XDC: imports/constraints/timing.xdc

# XDC: imports/constraints/auto.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_AXI_BayerToRGB_A_0/system_AXI_BayerToRGB_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_BayerToRGB_A_0 || ORIG_REF_NAME==system_AXI_BayerToRGB_A_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_BayerToRGB_B_0/system_AXI_BayerToRGB_B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_BayerToRGB_B_0 || ORIG_REF_NAME==system_AXI_BayerToRGB_B_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_BayerToRGB_C_0/system_AXI_BayerToRGB_C_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_BayerToRGB_C_0 || ORIG_REF_NAME==system_AXI_BayerToRGB_C_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_BayerToRGB_D_0/system_AXI_BayerToRGB_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_BayerToRGB_D_0 || ORIG_REF_NAME==system_AXI_BayerToRGB_D_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_GammaCorrection_A_0/system_AXI_GammaCorrection_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_GammaCorrection_A_0 || ORIG_REF_NAME==system_AXI_GammaCorrection_A_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_GammaCorrection_B_0/system_AXI_GammaCorrection_B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_GammaCorrection_B_0 || ORIG_REF_NAME==system_AXI_GammaCorrection_B_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_GammaCorrection_C_0/system_AXI_GammaCorrection_C_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_GammaCorrection_C_0 || ORIG_REF_NAME==system_AXI_GammaCorrection_C_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_GammaCorrection_D_0/system_AXI_GammaCorrection_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_AXI_GammaCorrection_D_0 || ORIG_REF_NAME==system_AXI_GammaCorrection_D_0} -quiet] -quiet

# IP: bd/system/ip/system_DVIClocking_0_0/system_DVIClocking_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_DVIClocking_0_0 || ORIG_REF_NAME==system_DVIClocking_0_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_CSI_2_RX_A_0/system_MIPI_CSI_2_RX_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_CSI_2_RX_A_0 || ORIG_REF_NAME==system_MIPI_CSI_2_RX_A_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_CSI_2_RX_B_0/system_MIPI_CSI_2_RX_B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_CSI_2_RX_B_0 || ORIG_REF_NAME==system_MIPI_CSI_2_RX_B_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_CSI_2_RX_C_0/system_MIPI_CSI_2_RX_C_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_CSI_2_RX_C_0 || ORIG_REF_NAME==system_MIPI_CSI_2_RX_C_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_CSI_2_RX_D_0/system_MIPI_CSI_2_RX_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_CSI_2_RX_D_0 || ORIG_REF_NAME==system_MIPI_CSI_2_RX_D_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_D_PHY_RX_A_0/system_MIPI_D_PHY_RX_A_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_D_PHY_RX_A_0 || ORIG_REF_NAME==system_MIPI_D_PHY_RX_A_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_D_PHY_RX_B_0/system_MIPI_D_PHY_RX_B_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_D_PHY_RX_B_0 || ORIG_REF_NAME==system_MIPI_D_PHY_RX_B_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_D_PHY_RX_C_0/system_MIPI_D_PHY_RX_C_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_D_PHY_RX_C_0 || ORIG_REF_NAME==system_MIPI_D_PHY_RX_C_0} -quiet] -quiet

# IP: bd/system/ip/system_MIPI_D_PHY_RX_D_0/system_MIPI_D_PHY_RX_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_MIPI_D_PHY_RX_D_0 || ORIG_REF_NAME==system_MIPI_D_PHY_RX_D_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cama_bta_0/system_axi_cama_bta_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cama_bta_0 || ORIG_REF_NAME==system_axi_cama_bta_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cama_gpio_0/system_axi_cama_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cama_gpio_0 || ORIG_REF_NAME==system_axi_cama_gpio_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_mem_intercon_1_0/system_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1_0 || ORIG_REF_NAME==system_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_a_0/system_axi_vdma_a_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_a_0 || ORIG_REF_NAME==system_axi_vdma_a_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_b_0/system_axi_vdma_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_b_0 || ORIG_REF_NAME==system_axi_vdma_b_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_c_0/system_axi_vdma_c_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_c_0 || ORIG_REF_NAME==system_axi_vdma_c_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_d_0/system_axi_vdma_d_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_d_0 || ORIG_REF_NAME==system_axi_vdma_d_0} -quiet] -quiet

# IP: bd/system/ip/system_cama_gpio_dir_0/system_cama_gpio_dir_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cama_gpio_dir_0 || ORIG_REF_NAME==system_cama_gpio_dir_0} -quiet] -quiet

# IP: bd/system/ip/system_cama_gpio_oen_0/system_cama_gpio_oen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cama_gpio_oen_0 || ORIG_REF_NAME==system_cama_gpio_oen_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_frame_ptr_concat_0/system_frame_ptr_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_frame_ptr_concat_0 || ORIG_REF_NAME==system_frame_ptr_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_irq_concat_0/system_irq_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_irq_concat_0 || ORIG_REF_NAME==system_irq_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rgb2vga_0_0/system_rgb2vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rgb2vga_0_0 || ORIG_REF_NAME==system_rgb2vga_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_clk_wiz_0_50M_0/system_rst_clk_wiz_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_0_50M_0 || ORIG_REF_NAME==system_rst_clk_wiz_0_50M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_system_150M_0/system_rst_system_150M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_system_150M_0 || ORIG_REF_NAME==system_rst_system_150M_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_vid_clk_dyn_0/system_rst_vid_clk_dyn_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_vid_clk_dyn_0 || ORIG_REF_NAME==system_rst_vid_clk_dyn_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_video_dynclk_0 || ORIG_REF_NAME==system_video_dynclk_0} -quiet] -quiet

# IP: bd/system/ip/system_video_scaler_a_0/system_video_scaler_a_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_video_scaler_a_0 || ORIG_REF_NAME==system_video_scaler_a_0} -quiet] -quiet

# IP: bd/system/ip/system_video_scaler_b_0/system_video_scaler_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_video_scaler_b_0 || ORIG_REF_NAME==system_video_scaler_b_0} -quiet] -quiet

# IP: bd/system/ip/system_video_scaler_c_0/system_video_scaler_c_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_video_scaler_c_0 || ORIG_REF_NAME==system_video_scaler_c_0} -quiet] -quiet

# IP: bd/system/ip/system_video_scaler_d_0/system_video_scaler_d_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_video_scaler_d_0 || ORIG_REF_NAME==system_video_scaler_d_0} -quiet] -quiet

# IP: bd/system/ip/system_vtg_0/system_vtg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_vtg_0 || ORIG_REF_NAME==system_vtg_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_6/system_s00_regslice_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s00_regslice_6 || ORIG_REF_NAME==system_s00_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_7/system_s00_regslice_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s00_regslice_7 || ORIG_REF_NAME==system_s00_regslice_7} -quiet] -quiet

# IP: bd/system/ip/system_s01_regslice_0/system_s01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s01_regslice_0 || ORIG_REF_NAME==system_s01_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_s02_regslice_0/system_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s02_regslice_0 || ORIG_REF_NAME==system_s02_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_s03_regslice_0/system_s03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s03_regslice_0 || ORIG_REF_NAME==system_s03_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_0/system_m00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_m00_regslice_0 || ORIG_REF_NAME==system_m00_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_8/system_s00_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s00_regslice_8 || ORIG_REF_NAME==system_s00_regslice_8} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_2/system_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_3/system_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_cc_3 || ORIG_REF_NAME==system_auto_cc_3} -quiet] -quiet

# XDC: d:/workspace/fbga_project/dual_demo/hw/hw.gen/sources_1/bd/system/system_ooc.xdc
