# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/workspace/fbga_project/dual_demo/hw/hw.srcs/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7.xci
# IP: The module: 'system_s00_regslice_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/fbga_project/dual_demo/hw/hw.gen/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/workspace/fbga_project/dual_demo/hw/hw.gen/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/workspace/fbga_project/dual_demo/hw/hw.srcs/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7.xci
# IP: The module: 'system_s00_regslice_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workspace/fbga_project/dual_demo/hw/hw.gen/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/workspace/fbga_project/dual_demo/hw/hw.gen/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
