
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_CAMA_BTA_DEVICE_ID,
		XPAR_AXI_CAMA_BTA_BASEADDR,
		XPAR_AXI_CAMA_BTA_INTERRUPT_PRESENT,
		XPAR_AXI_CAMA_BTA_IS_DUAL
	},
	{
		XPAR_AXI_CAMA_GPIO_DEVICE_ID,
		XPAR_AXI_CAMA_GPIO_BASEADDR,
		XPAR_AXI_CAMA_GPIO_INTERRUPT_PRESENT,
		XPAR_AXI_CAMA_GPIO_IS_DUAL
	}
};


