#ifndef XPARAMETERS_H
#define XPARAMETERS_H

/* Mock xparameters.h - CI/CD icin */

#define XPAR_XUARTPS_0_BASEADDR         0xE0000000
#define XPAR_XUARTPS_0_CLOCK_HZ         100000000
#define XPAR_XEMACPS_0_BASEADDR         0xE000B000
#define XPAR_XEMACPS_0_PHY_TYPE         0
#define XPAR_SCUGIC_0_CPU_BASEADDR      0xF8F00100
#define XPAR_SCUGIC_0_DIST_BASEADDR     0xF8F01000
#define XPAR_SCUGIC_SINGLE_DEVICE_ID    0
#define XPAR_XIICPS_0_DEVICE_ID         0
#define XPAR_XIICPS_0_CLOCK_HZ          100000000
#define XPAR_XGPIOPS_0_DEVICE_ID        0
#define XPAR_MIPI_D_PHY_RX_NUM_INSTANCES 2
#define XPAR_GIGE_PCS_PMA_SGMII_CORE_PRESENT 1

#endif