
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvideo_scaler.h"

/*
* The configuration table for devices
*/

XVideo_scaler_Config XVideo_scaler_ConfigTable[XPAR_XVIDEO_SCALER_NUM_INSTANCES] =
{
	{
		XPAR_VIDEO_SCALER_A_DEVICE_ID,
		XPAR_VIDEO_SCALER_A_S_AXI_CTRL_BASEADDR
	},
	{
		XPAR_VIDEO_SCALER_B_DEVICE_ID,
		XPAR_VIDEO_SCALER_B_S_AXI_CTRL_BASEADDR
	},
	{
		XPAR_VIDEO_SCALER_C_DEVICE_ID,
		XPAR_VIDEO_SCALER_C_S_AXI_CTRL_BASEADDR
	},
	{
		XPAR_VIDEO_SCALER_D_DEVICE_ID,
		XPAR_VIDEO_SCALER_D_S_AXI_CTRL_BASEADDR
	}
};


