# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/arsla/Downloads/5-6/project5_muxdemux/project5_muxdemux.srcs/constrs_1/new/basys3.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_0_0/design_1_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux_0_0 || ORIG_REF_NAME==design_1_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_demux_0_0/design_1_demux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_demux_0_0 || ORIG_REF_NAME==design_1_demux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_counter_0_1/design_1_counter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_counter_0_1 || ORIG_REF_NAME==design_1_counter_0_1} -quiet] -quiet

# XDC: d:/workspace/LAB/section5_1/project_3.gen/sources_1/bd/design_1/design_1_ooc.xdc
